create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  name text not null,
  species text,
  class text,
  alignment text,
  background text,
  biography text,
  abilities text,
  affiliation text,
  status text,
  image_url text,
  notes text,
  created_at timestamp with time zone not null default now()
);

alter table public.characters enable row level security;

create policy "Anyone can view characters"
on public.characters
for select
to anon, authenticated
using (true);

create policy "Authenticated users can create characters"
on public.characters
for insert
to authenticated
with check (true);

create policy "Authenticated users can update characters"
on public.characters
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete characters"
on public.characters
for delete
to authenticated
using (true);

insert into public.characters
  (name, species, class, alignment, background, biography, abilities, affiliation, status, image_url, notes)
values
  (
    'Aelira Moonbrook',
    'Half-Elf',
    'Ranger',
    'Neutral Good',
    'Borderland scout',
    'Aelira maps forgotten roads and keeps watch over ruined watchtowers on the edge of settled lands.',
    'Tracking, archery, wilderness survival',
    'Moonbrook Wardens',
    'Active',
    '',
    'Original sample character for testing.'
  ),
  (
    'Bram Ironvale',
    'Dwarf',
    'Cleric',
    'Lawful Good',
    'Traveling shrine-keeper',
    'Bram carries records of lost clans, battlefield oaths, and names that should not be forgotten.',
    'Healing, protective wards, historical records',
    'Order of the Lantern Vault',
    'Active',
    '',
    'Original sample character for testing.'
  ),
  (
    'Nyx Emberquill',
    'Tiefling',
    'Wizard',
    'Chaotic Neutral',
    'Archive mage',
    'Nyx studies cursed manuscripts and catalogues magical anomalies before they can damage the realm.',
    'Arcane research, curse analysis, ritual magic',
    'The Sable Athenaeum',
    'Missing',
    '',
    'Original sample character for testing.'
  );